alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: aeriusbacklog.nl
    type: PRIMARY
    zone: aeriusbacklog.nl
features:
  - buildpack-stack=ubuntu-22
name: backlog-tooling
region: ams
services:
  - build_command: cd frontend && npm ci && npm run build && cd ../api && npm ci && npm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: JornC/backlog-tooling
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    name: app
    run_command: node api/dist/server.js
