service: backlog
image: jornc/backlog-tooling

servers:
  web:
    hosts:
      - 128.140.14.118

proxy:
  host: aeriusbacklog.nl
  ssl: true
  app_port: 8080
  healthcheck:
    path: /api/ping

registry:
  server: ghcr.io
  username: JornC
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - JIRA_USER
    - JIRA_API_TOKEN
    - SMTP_USER
    - SMTP_PASS
    - SMTP_TO

builder:
  arch: arm64
  remote: ssh://root@128.140.14.118
