/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationNavigation: typeof import('./components/nav/ApplicationNavigation.vue')['default']
    copy: typeof import('./components/signals/SignalButton copy.vue')['default']
    EstimationPoker: typeof import('./components/signals/EstimationPoker.vue')['default']
    PokerButton: typeof import('./components/signals/PokerButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignalButton: typeof import('./components/signals/SignalButton.vue')['default']
    SimpleSignals: typeof import('./components/signals/SimpleSignals.vue')['default']
  }
}
