/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationNavigation: typeof import('./components/nav/ApplicationNavigation.vue')['default']
    EstimationPoker: typeof import('./components/signals/EstimationPoker.vue')['default']
    MeetingControls: typeof import('./components/mod/MeetingControls.vue')['default']
    PinControls: typeof import('./components/mod/PinControls.vue')['default']
    PinGate: typeof import('./components/PinGate.vue')['default']
    PokerButton: typeof import('./components/signals/PokerButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scratchboard: typeof import('./components/signals/Scratchboard.vue')['default']
    SessionControls: typeof import('./components/mod/SessionControls.vue')['default']
    SignalButton: typeof import('./components/signals/SignalButton.vue')['default']
    SimpleSignals: typeof import('./components/signals/SimpleSignals.vue')['default']
    UserControls: typeof import('./components/mod/UserControls.vue')['default']
    UserPanel: typeof import('./components/mod/UserPanel.vue')['default']
  }
}
